/* TGC entry pilot v17. Same-origin adapter for the unchanged, field-tested v15
   scanner. All records and images stay on the device; no fetch/upload endpoints. */
(()=>{'use strict';
const $=id=>document.getElementById(id),host=$('scanHost');
const slots=[['front','Vorne',true],['rear','Hinten',true],['left','Fahrerseite',true],['right','Beifahrerseite',true],['inside','Innenraum',false],['odo','Tacho',false]];
const fields=['operator','site','plate','customer','reference','carrier','mileage','notes'];
const vinOK=v=>/^[A-HJ-NPR-Z0-9]{17}$/.test(v);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
let current=null,resumable=null,displayed=null,reporting=null,scannerReady=false,step='scan',returnStep='done',busy=false,scanningAccepted=false;
let db=null,saveTimer=null,queue=Promise.resolve(),lastSaved=false,photoUrls=[],reportUrls=[],observer=null,resize=null;
const date=v=>new Date(v).toLocaleString('de-DE');
function message(text){$('saveState').textContent=text;}
function error(text=''){$('error').textContent=text;$('error').hidden=!text;if(text)$('error').scrollIntoView({block:'center',behavior:'smooth'});}
function stopScan(){try{if(scannerReady)host.contentWindow.stop(true);}catch(e){}}
function screen(name){step=name;for(const n of ['scan','photos','review','done','report'])$(n+'Screen').hidden=n!==name;document.querySelectorAll('[data-step]').forEach(el=>el.classList.toggle('active',el.dataset.step===name));if(name!=='scan')stopScan();$('archive').hidden=name==='photos'||name==='review'||name==='report';error();window.scrollTo({top:0,behavior:'smooth'});}
function clone(e){return {...e,meta:{...e.meta},photos:e.photos.map(p=>({...p})),source:{...e.source}};}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('tgc-fahrzeugeingang-v16',1);req.onupgradeneeded=()=>{for(const [name,key] of [['draft','key'],['records','id'],['list','id']])req.result.createObjectStore(name,{keyPath:key});};req.onsuccess=()=>{db=req.result;db.onversionchange=()=>db.close();resolve(db);};req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('Lokaler Speicher blockiert'));});}
function tx(names,fn){return new Promise((resolve,reject)=>{if(!db){reject(new Error('Kein lokaler Speicher'));return;}let t;try{t=db.transaction(names,'readwrite');fn(t);}catch(e){reject(e);return;}t.oncomplete=()=>resolve();t.onabort=()=>reject(t.error||new Error('Speichern abgebrochen'));t.onerror=()=>{};});}
function read(store,key){return new Promise((resolve,reject)=>{if(!db){resolve(null);return;}const req=db.transaction(store).objectStore(store).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function summaries(){return new Promise((resolve,reject)=>{if(!db){resolve([]);return;}const req=db.transaction('list').objectStore('list').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function changed(){if(!current||current.state!=='draft')return;current.updatedAt=new Date().toISOString();lastSaved=false;clearTimeout(saveTimer);message('Änderungen werden lokal gespeichert …');saveTimer=setTimeout(()=>saveDraft(),300);}
function saveDraft(){clearTimeout(saveTimer);if(!current||current.state!=='draft')return queue;const snapshot=clone(current),revision=snapshot.updatedAt;
 queue=queue.catch(()=>{}).then(()=>tx(['draft'],t=>t.objectStore('draft').put({key:'current',entry:snapshot}))).then(()=>{if(current?.id===snapshot.id&&current.updatedAt===revision){lastSaved=true;message('Entwurf gespeichert · nur auf diesem Gerät');}}).catch(()=>{lastSaved=false;message('Nicht gespeichert: nur im Arbeitsspeicher. Browser nicht schließen; Protokoll exportieren.');});return queue;}
function resetScanner(){scanningAccepted=false;try{const d=host.contentDocument;d.getElementById('result').hidden=true;d.getElementById('vin').value='';stopScan();}catch(e){}}
function bindScanner(){
 try{const d=host.contentDocument,box=d.getElementById('result'),v=d.getElementById('vin');if(!box||!v)throw new Error('Scanner-Oberfläche nicht verfügbar');scannerReady=true;
  // Presentation only; decoder, camera settings and live scan path remain untouched.
  const style=d.createElement('style');style.textContent='header,footer{display:none!important}.app{padding:0 4px 14px}h1{margin-top:12px}';d.head.append(style);
  const size=()=>{const body=d.querySelector('main.app');if(body)host.style.height=Math.ceil(body.getBoundingClientRect().height+24)+'px';};size();resize?.disconnect();resize=new ResizeObserver(size);resize.observe(d.querySelector('main.app'));
  observer?.disconnect();observer=new MutationObserver(()=>{if(box.hidden||step!=='scan'||scanningAccepted)return;const value=v.value.trim();if(!vinOK(value)){error('Der Scanner hat keine vollständige VIN geliefert.');return;}scanningAccepted=true;const source=d.getElementById('resultInfo')?.textContent||'Code 39';begin(value,{kind:'barcode',detail:source});});observer.observe(box,{attributes:true,attributeFilter:['hidden'],childList:true,subtree:true});
 }catch(e){error('Scanner konnte hier nicht eingebunden werden. Den separaten Barcode-HD-Link verwenden oder VIN manuell eingeben.');}
}
host.addEventListener('load',bindScanner);if(host.contentDocument?.readyState==='complete'&&host.contentDocument.getElementById('result'))bindScanner();
async function begin(v,source){
 if(busy)return;if(resumable&&!current){if(!confirm('Den offenen Entwurf verwerfen und dieses Fahrzeug neu erfassen?')){resetScanner();return;}try{await tx(['draft'],t=>t.objectStore('draft').delete('current'));}catch(e){}resumable=null;showResume();}
 const now=new Date().toISOString();current={id:uid(),version:17,state:'draft',vin:v,source,startedAt:now,updatedAt:now,completedAt:null,confirmed:false,inspection:'',meta:Object.fromEntries(fields.map(k=>[k,''])),photos:[]};hydrate();screen('photos');changed();
}
function showResume(){$('resumeBox').hidden=!resumable;$('resumeText').textContent=resumable?resumable.vin+' · '+resumable.photos.length+' Foto(s) · '+date(resumable.updatedAt):'';}
function hydrate(){$('entryVin').textContent=current.vin;$('vinSource').textContent=current.source.kind==='barcode'?'VIN aus TGC-Barcode übernommen':'VIN manuell eingegeben';$('vinConfirmed').checked=current.confirmed;for(const f of fields)$(f).value=current.meta[f]||'';$('inspectionNone').checked=current.inspection==='none';$('inspectionDamage').checked=current.inspection==='damage';$('finalConfirmed').checked=false;renderPhotos();}
function release(urls){for(const u of urls)URL.revokeObjectURL(u);urls.length=0;}
function imageURL(blob,collection=photoUrls){const url=URL.createObjectURL(blob);collection.push(url);return url;}
function photoLabel(p){return slots.find(s=>s[0]===p.slot)?.[1]||'Detailaufnahme';}
function renderPhotos(){
 release(photoUrls);const grid=$('photoGrid');grid.textContent='';const extra=current.photos.filter(p=>p.slot.startsWith('extra-')).map(p=>[p.slot,'Detailaufnahme',false]);
 for(const [slot,title,required] of [...slots,...extra]){
  const p=current.photos.find(x=>x.slot===slot),card=document.createElement('article');card.className='photo';card.dataset.slot=slot;
  card.innerHTML='<div class="photo-top"><strong>'+esc(title)+'</strong><small>'+(required?'Pflichtfoto':'optional')+'</small></div><button type="button" class="photo-shot '+(p?'has-photo':'')+'" aria-label="'+esc(title)+(p?' erneut fotografieren':' fotografieren')+'">'+(p?'<img alt="'+esc(title)+'" src="'+imageURL(p.thumb||p.blob)+'">':'')+'<span class="shot-label">'+(p?'Foto ersetzen':'📷 Foto aufnehmen')+'</span></button><input class="file" hidden type="file" accept="image/*" capture="environment"><div class="photo-body">'+(p?'<label class="check"><input class="damage-toggle" type="checkbox" '+(p.damage?'checked':'')+'><span>Schaden an diesem Foto</span></label><div class="damage-fields" '+(p.damage?'':'hidden')+'><label class="field">Schadenstelle<input class="location" type="text" maxlength="140" value="'+esc(p.location)+'"></label><label class="field">Schadenart<select class="type"><option value="">Bitte wählen</option>'+['Kratzer','Delle','Lackschaden','Felgenschaden','Glasschaden','Innenraumschaden','Sonstiges'].map(x=>'<option '+(x===p.type?'selected':'')+'>'+x+'</option>').join('')+'</select></label><label class="field">Beschreibung<textarea class="note" maxlength="1500" placeholder="z. B. Stoßfänger hinten rechts, Kratzer ca. 8 cm">'+esc(p.note)+'</textarea></label></div><button type="button" class="remove">Foto entfernen</button>':'<small>Foto antippen, aufnehmen und übernehmen.</small>')+'</div>';
  const file=card.querySelector('input[type=file]');card.querySelector('.photo-shot').onclick=()=>{if(!busy)file.click();};file.onchange=e=>addPhoto(e.target.files[0],slot);
  if(p){card.querySelector('.damage-toggle').onchange=e=>{p.damage=e.target.checked;card.querySelector('.damage-fields').hidden=!p.damage;if(p.damage){current.inspection='damage';$('inspectionDamage').checked=true;}counts();changed();};
   for(const [cls,key] of [['location','location'],['type','type'],['note','note']])card.querySelector('.'+cls).addEventListener('input',e=>{p[key]=e.target.value;changed();});
   card.querySelector('.remove').onclick=()=>{if(busy)return;if(!confirm('Dieses Foto einschließlich seiner Schadenmarkierung entfernen?'))return;current.photos=current.photos.filter(x=>x.id!==p.id);renderPhotos();changed();};}
  grid.append(card);
 }counts();}
function counts(){const n=slots.filter(s=>s[2]&&current.photos.some(p=>p.slot===s[0])).length,d=current.photos.filter(p=>p.damage).length;$('photoCount').textContent=n+'/4 Außenansichten · '+current.photos.length+' Foto(s) · '+d+' Schadenmarkierung(en)';}
function lock(value){busy=value;for(const id of ['reviewBtn','finishBtn','addDetail','changeVehicle','manualBtn','nextVehicle'])$(id).disabled=value;document.querySelectorAll('.photo-shot,.remove').forEach(el=>el.disabled=value);}
async function thumbnail(file){const u=URL.createObjectURL(file);try{const im=new Image();im.src=u;await im.decode();const c=document.createElement('canvas'),s=Math.min(1,640/Math.max(im.naturalWidth,im.naturalHeight));c.width=Math.max(1,Math.round(im.naturalWidth*s));c.height=Math.max(1,Math.round(im.naturalHeight*s));c.getContext('2d').drawImage(im,0,0,c.width,c.height);return await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('Vorschaubild nicht verfügbar')),'image/jpeg',.82));}finally{URL.revokeObjectURL(u);}}
async function addPhoto(file,slot){
 if(!file||busy)return;error();if(file.size>25*1024*1024){error('Dieses Foto ist größer als 25 MB. Bitte ein kleineres Bild verwenden.');return;}if(!current.photos.some(p=>p.slot===slot)&&current.photos.length>=24){error('Für diesen Test sind maximal 24 Fotos je Eingang vorgesehen.');return;}
 const identity=current.id;lock(true);message('Foto wird auf diesem Gerät übernommen …');
 try{const thumb=await thumbnail(file);if(current?.id!==identity)return;const old=current.photos.find(p=>p.slot===slot),p={id:old?.id||uid(),slot,blob:file,thumb,takenAt:new Date().toISOString(),damage:old?.damage||false,location:old?.location||slots.find(s=>s[0]===slot)?.[1]||'',type:old?.type||'',note:old?.note||''};current.photos=current.photos.filter(p=>p.slot!==slot);current.photos.push(p);renderPhotos();changed();await saveDraft();}
 catch(e){error('Foto konnte nicht geöffnet werden. Bitte erneut aufnehmen oder ein JPEG-/PNG-Foto auswählen.');}finally{lock(false);}
}
const extraFile=document.createElement('input');extraFile.type='file';extraFile.accept='image/*';extraFile.setAttribute('capture','environment');extraFile.hidden=true;document.body.append(extraFile);extraFile.onchange=e=>{addPhoto(e.target.files[0],'extra-'+uid());extraFile.value='';};
function problems(){const out=[];if(!current?.confirmed)out.push('VIN mit dem Fahrzeugzettel vergleichen und bestätigen.');if(!current?.meta.operator.trim())out.push('Mitarbeiter / Kürzel eintragen.');const missing=slots.filter(s=>s[2]&&!current.photos.some(p=>p.slot===s[0]));if(missing.length)out.push('Pflichtfotos fehlen: '+missing.map(s=>s[1]).join(', '));if(!current.inspection)out.push('Schadenprüfung auswählen.');const damage=current.photos.filter(p=>p.damage);if(current.inspection==='none'&&damage.length)out.push('Schadenmarkierungen und „keine Schäden“ widersprechen sich.');if(current.inspection==='damage'&&!damage.length)out.push('Mindestens ein Foto als Schaden markieren und beschreiben.');for(const p of damage)if(!p.location.trim()||!p.type||!p.note.trim())out.push(photoLabel(p)+': Schadenstelle, Schadenart und Beschreibung ergänzen.');if(current.meta.mileage!==''&&(!/^\d+$/.test(current.meta.mileage)||Number(current.meta.mileage)>9999999))out.push('Kilometerstand als ganze positive Zahl oder 0 eingeben.');return out;}
function summary(e){const pairs=[['VIN',e.vin],['Erfasst',date(e.startedAt)],['Mitarbeiter',e.meta.operator],['Standort',e.meta.site],['Kennzeichen',e.meta.plate],['Kunde',e.meta.customer],['Auftrag',e.meta.reference],['Spediteur',e.meta.carrier],['Kilometer',e.meta.mileage],['Fotos',e.photos.length],['Schäden',e.inspection==='damage'?e.photos.filter(p=>p.damage).length+' markiert':'Keine sichtbaren Schäden festgestellt'],['Notizen',e.meta.notes]];return pairs.map(([k,v])=>'<div class="summary-line"><strong>'+esc(k)+'</strong><span>'+esc(v===''?'–':v)+'</span></div>').join('');}
async function review(){if(busy)return;const p=problems();if(p.length){error(p.join('\n'));return;}await saveDraft();$('reviewSummary').innerHTML=summary(current);$('reviewPhotos').textContent='';for(const p of current.photos){const card=document.createElement('div');card.className='photo';card.innerHTML='<div class="photo-top"><strong>'+esc(photoLabel(p))+'</strong></div><div class="photo-shot"><img alt="'+esc(photoLabel(p))+'" src="'+imageURL(p.thumb||p.blob)+'"></div><div class="photo-body">'+(p.damage?'<strong>'+esc(p.type)+'</strong><p>'+esc(p.location)+'<br>'+esc(p.note)+'</p>':'<small>Keine Schadenmarkierung an diesem Foto</small>')+'</div>';$('reviewPhotos').append(card);}screen('review');}
function smallRecord(e){return {id:e.id,vin:e.vin,completedAt:e.completedAt,photos:e.photos.length,damages:e.photos.filter(p=>p.damage).length,operator:e.meta.operator};}
async function finish(){if(busy)return;const p=problems();if(p.length){screen('photos');error(p.join('\n'));return;}if(!$('finalConfirmed').checked){error('Bitte die Abschlusskontrolle bestätigen.');return;}lock(true);await saveDraft();await queue;clearTimeout(saveTimer);const completed={...clone(current),state:'completed',completedAt:new Date().toISOString()};let saved=false;
 try{await tx(['records','list','draft'],t=>{t.objectStore('records').put(completed);t.objectStore('list').put(smallRecord(completed));t.objectStore('draft').delete('current');});saved=true;}catch(e){}
 current=completed;displayed=completed;resumable=null;lastSaved=saved;showDone(saved);await renderArchive();lock(false);
}
function showDone(saved){$('doneTitle').textContent=saved?'Eingang lokal abgeschlossen':'Abgeschlossen – noch nicht gespeichert';$('doneSummary').innerHTML=summary(displayed);$('doneNote').textContent=saved?'Fotos und Daten sind in diesem Browser gespeichert. Nicht im TGC-System und nicht für andere Geräte sichtbar. Protokoll zur Sicherung exportieren.':'Speichern im Browser fehlgeschlagen. Daten sind nur im Arbeitsspeicher. Jetzt das Protokoll exportieren, bevor diese Seite geschlossen wird.';message(saved?'Lokal gespeichert · keine Übertragung / keine E-Mail':'Nur im Arbeitsspeicher · Export erforderlich');screen('done');}
function reportMarkup(e,urls){return '<h1>TGC · Eingangsprotokoll</h1><p class="testlabel">TESTPROTOKOLL · lokale Erfassung · kein Cargo-/SFK-Auftrag · keine Haftbarkeitsmail versendet</p><p><strong>Protokoll-ID:</strong> '+esc(e.id)+'<br><strong>Abgeschlossen:</strong> '+esc(date(e.completedAt))+'<br><strong>VIN-Erfassung:</strong> '+esc(e.source.kind==='barcode'?'TGC Barcode / Code 39':'Manuelle Eingabe')+'<br><strong>VIN geprüft:</strong> '+(e.confirmed?'Vom Mitarbeiter bestätigt':'Nicht bestätigt')+'</p>'+summary(e)+'<h2>Fotos und Schadenmarkierungen</h2><div class="photo-grid">'+e.photos.map((p,i)=>'<figure><img src="'+urls[i]+'" alt="'+esc(photoLabel(p))+'"><figcaption><strong>'+esc(photoLabel(p))+'</strong> · übernommen '+esc(date(p.takenAt))+'<br>'+(p.damage?'SCHADEN: '+esc(p.location)+' · '+esc(p.type)+'<br>'+esc(p.note):'Keine Schadenmarkierung an diesem Foto')+'</figcaption></figure>').join('')+'</div><p><small>Zeitangaben stammen vom erfassenden Gerät. „Keine Schadenmarkierung“ ersetzt keine vollständige Zustandsprüfung.</small></p>';}
function showReport(entry=displayed){if(!entry)return;reporting=entry;returnStep=step;release(reportUrls);const urls=entry.photos.map(p=>imageURL(p.blob,reportUrls));$('report').innerHTML=reportMarkup(entry,urls);screen('report');}
function dataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});}
async function exportEntry(){const entry=step==='report'?reporting:displayed;if(!entry)return;const buttons=[$('exportDone'),$('exportReport')];buttons.forEach(b=>b.disabled=true);message('Protokoll inklusive Originalfotos wird vorbereitet …');
 try{const e=entry,urls=[];for(const p of e.photos)urls.push(await dataURL(p.blob));const html='<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TGC Eingang '+esc(e.vin)+'</title><style>body{font:15px/1.5 Arial,sans-serif;max-width:950px;margin:24px auto;padding:20px;color:#152031}h1{font-size:27px}.summary-line{display:grid;grid-template-columns:145px 1fr;gap:12px;border-bottom:1px solid #ddd;padding:8px 0;overflow-wrap:anywhere}.testlabel{border:1px solid #b48322;padding:10px}.photo-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:8px 0;break-inside:avoid}img{width:100%;max-height:450px;object-fit:contain}figcaption{font-size:13px;white-space:pre-line}small{color:#56616f}@media(max-width:550px){.photo-grid{grid-template-columns:1fr}}@media print{@page{size:A4;margin:14mm}body{margin:0;padding:0}.photo-grid{grid-template-columns:1fr 1fr}img{max-height:95mm}}</style></head><body>'+reportMarkup(e,urls)+'</body></html>';const blob=new Blob([html],{type:'text/html;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='TGC_Eingang_'+e.vin+'_'+e.id.slice(0,8)+'.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),120000);message('Protokolldatei bereitgestellt. Export auf deinem Gerät sichern.');}
 catch(e){error('Export fehlgeschlagen. Seite geöffnet lassen und erneut versuchen.');}finally{buttons.forEach(b=>b.disabled=false);}
}
async function renderArchive(){try{const entries=await summaries();entries.sort((a,b)=>b.completedAt.localeCompare(a.completedAt));$('archiveCount').textContent='('+entries.length+')';$('archiveList').textContent=entries.length?'':'Noch keine abgeschlossenen Eingänge.';for(const item of entries){const div=document.createElement('div');div.className='record';div.innerHTML='<strong>'+esc(item.vin)+'</strong><small>'+esc(date(item.completedAt))+' · '+item.photos+' Fotos · '+item.damages+' Schäden</small><div class="row"><button class="open">Protokoll öffnen</button><button class="delete">Lokal löschen</button></div>';div.querySelector('.open').onclick=async()=>{try{const entry=await read('records',item.id);if(entry)showReport(entry);}catch(e){error('Gespeicherten Eingang nicht gefunden.');}};div.querySelector('.delete').onclick=async()=>{if(!confirm('Diesen gespeicherten Eingang mit allen Fotos nur auf diesem Gerät löschen?'))return;try{await tx(['records','list'],t=>{t.objectStore('records').delete(item.id);t.objectStore('list').delete(item.id);});await renderArchive();}catch(e){error('Löschen fehlgeschlagen.');}};$('archiveList').append(div);}}catch(e){$('archiveList').textContent='Lokales Archiv nicht verfügbar.';}}
async function startNew(){if(busy)return;if(current?.state==='completed'&&!lastSaved&&!confirm('Dieser Eingang wurde nicht im Browser gespeichert. Protokoll exportiert? Ohne Speicherung neu anfangen?'))return;if(current?.state==='draft'){if(!confirm('Diesen Entwurf inklusive Fotos verwerfen und neu scannen?'))return;clearTimeout(saveTimer);await queue;try{await tx(['draft'],t=>t.objectStore('draft').delete('current'));}catch(e){}}
 current=null;displayed=null;resumable=null;release(photoUrls);release(reportUrls);showResume();resetScanner();screen('scan');message('Bereit für den nächsten Fahrzeugeingang.');}
$('manualBtn').onclick=()=>{const v=$('manualVin').value.trim().toUpperCase();if(!vinOK(v)){error('Bitte genau 17 VIN-Zeichen eingeben. Keine Zeichen werden ersetzt oder geraten.');return;}begin(v,{kind:'manual',detail:'Manuell eingegeben'});};
$('resumeBtn').onclick=()=>{current=resumable;resumable=null;showResume();hydrate();screen('photos');message('Lokalen Entwurf wiederhergestellt.');};$('discardBtn').onclick=async()=>{if(!confirm('Den offenen Entwurf mit seinen Fotos löschen?'))return;try{await tx(['draft'],t=>t.objectStore('draft').delete('current'));resumable=null;showResume();}catch(e){error('Entwurf konnte nicht gelöscht werden.');}};
$('vinConfirmed').onchange=e=>{current.confirmed=e.target.checked;changed();};for(const f of fields)$(f).oninput=e=>{current.meta[f]=e.target.value;changed();};for(const id of ['inspectionNone','inspectionDamage'])$(id).onchange=e=>{current.inspection=e.target.value;changed();};$('addDetail').onclick=()=>{if(!busy)extraFile.click();};$('changeVehicle').onclick=startNew;$('nextVehicle').onclick=startNew;$('reviewBtn').onclick=review;$('backPhotos').onclick=()=>{screen('photos');};$('finishBtn').onclick=finish;$('viewReport').onclick=()=>showReport();$('exportDone').onclick=exportEntry;$('exportReport').onclick=exportEntry;$('closeReport').onclick=()=>{release(reportUrls);$('report').textContent='';reporting=null;screen(returnStep);};$('printReport').onclick=()=>window.print();
window.addEventListener('beforeunload',e=>{if(busy||(current?.state==='draft'&&!lastSaved)){e.preventDefault();e.returnValue='';}});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopScan();saveDraft();}});
(async()=>{try{await openDB();const d=await read('draft','current');if(d?.entry?.state==='draft'&&vinOK(d.entry.vin)){resumable=d.entry;showResume();}message('Lokaler Speicher bereit · keine Datenübertragung');}catch(e){message('Lokaler Speicher nicht verfügbar. Test nur im Arbeitsspeicher.');}await renderArchive();})();

// Read-only access to the completed entry for the local mail-draft module.
window.TGCEntryMailContext=()=>step==='report'?reporting:step==='done'?displayed:null;
})();
